Allow only supported image file formats
Ocelot-Social-Community/Ocelot-Social pull request #3928
Opened 2020-10-27 07:24 UTC by dasari810

## 🍰 Pullrequest

- to automatically  filter only the supported image file formats when the user uploads the image for creating post 

- to give an error message if an unsupported file format is uploaded ( post will not be created ) 

### Issues

- fixes #3923 

### Todo

- [X] None

2020-10-29 18:51 UTC, Tirokk commented
Hey @dasari810 ,
sorry for not caring. I have to help somebody as an emergency who has problems with corona in his family. Because of this and other things unfortunately I need til Monday to find time for your PR. 😓

2020-10-29 19:06 UTC, dasari810 commented
hey @Tirokk  it's completely fine  :+1:  , and also take care of your self in these difficult situations :blush:

2020-11-02 11:51 UTC, Tirokk requested changes
Hey @dasari810 ,
nice that you did this PR as well. 🚀💫

This makes thinks much more clear and brings our project forward !!!

I have little changes requested …

2020-11-02 11:51 UTC, Tirokk commented on webapp/components/ImageUploader/ImageUploader.spec.js
> +        'Please upload an image of file format : jpg , jpeg , png or gif'
If you add a translation, then check for its identifier here …

2020-11-02 11:51 UTC, Tirokk commented on webapp/components/ImageUploader/ImageUploader.spec.js
> +      it('shows an error toaster when unSupported file is uploaded', () => {
Cool that you implemented a test for the toast message! 🤗😎
@dasari810 👍🏼

2020-11-02 11:51 UTC, Tirokk commented on webapp/components/ImageUploader/ImageUploader.vue
> +          'Please upload an image of file format : jpg , jpeg , png or gif',
Please lets use locales for translations here @dasari810 🙏🏼
That the users have their languages.

Would be nice if you can write the possible file formats as capitals like in your other PR #3925 . 🤗

2020-11-03 14:34 UTC, Tirokk approved these changes
Hey cool @dasari810 ,
thanks for contributing again !!! 🚀💫

A nice next step for a better user experience!

PS: I allowed my self to add the German language and add the branch `3921-set-up-travis-builds` so that the Travis builds can run now …

PPS: In case you are keen on being perfect:
There are two toast messages if an error occurs. But I already approved your PR … 🤗

<img width="1876" alt="Bildschirmfoto 2020-11-03 um 15 15 29" src="https://user-images.githubusercontent.com/25344101/97997935-cc790200-1de9-11eb-9d05-588ed20138e3.png">

2020-11-03 18:55 UTC, dasari810 commented
yeah @Tirokk  , i will try to resolve it .

2020-11-04 09:16 UTC, Tirokk commented
Hey cool! 👍🏼😎😁

PS: I merged new master with Travis working now in your branch

2020-11-16 13:22 UTC, Tirokk commented
Shall I merge it @dasari810 and we create an additional issue?

2021-02-04 14:21 UTC, Mogge commented
@dasari810 I merge this PR. Thank you very much for your contribution. I am looking forward to see you again!

2021-02-04 14:22 UTC, merged