Replacement PR From Current Repository For [WIP] fix: 🍰 Issue #3504 umlaut encoding #3676
Ocelot-Social-Community/Ocelot-Social pull request #4104
Opened 2020-12-29 19:59 UTC by Brandon-G-Tripp

This PR is a replacement for PR #3676. The previous PR was from the old HC repository and has issues with the merge. The setting for the slug package has been set to properly resolve the umlauts to their proper two letter encoding. 

## 🍰 Pullrequest

### Issues

- fixes #3504  

### Todo

- [X] None

2021-01-06 21:18 UTC, Brandon-G-Tripp commented
@Tirokk @Mogge @ulfgebhardt This pull request should be ready to merge and we can close the old one after that is from the old HC.

2021-01-11 09:55 UTC, Mogge requested changes
Thank you very much for your contribution. As far as I can see, the Umlauts resolve different as expected.
I change the title of the PR because it will appear in the changelog of the next release.

2021-01-11 09:55 UTC, Mogge commented on backend/src/middleware/slugify/uniqueSlug.spec.js
> +describe('Slug is transliterated correctly', () => {
Please have only one top level describe block. You can easily move the second one inside the first one.

2021-01-11 09:55 UTC, Mogge commented on backend/src/middleware/slugify/uniqueSlug.spec.js
> +    expect(uniqueSlug(umlaut, isUnique)).resolves.toEqual('ae')
This is the message I get:
```
Expected: "ae"
Received: "a"
(node:18852) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18852) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
What we need is a `async` call:
```javascript
  it('Converts umlaut to a two letter equivalent', async () => {
  ...
  await expect(uniqueSlug(umlaut, isUnique)).resolves.toEqual('ae')
```
The you will get an error. It resolves to `a`

2021-01-12 05:21 UTC, Brandon-G-Tripp commented
@Mogge thanks for taking a look!

2021-01-15 00:08 UTC, Brandon-G-Tripp commented
@Mogge The update did not resolve the issue so I included the Char map to pass the tests and get the issue out of the way.

2021-01-20 23:22 UTC, Mogge requested changes
You are close! Thank you for your affords.

2021-01-20 23:22 UTC, Mogge commented on backend/src/middleware/slugify/uniqueSlug.js
> +    charmap: { Ä: 'AE', ä: 'ae', Ö: 'OE', ö: 'oe', Ü: 'UE', ü: 'ue', ñ: 'n' },
You are missing:
```
'ß': 'ss'
```

2021-01-20 23:22 UTC, Mogge commented on backend/src/middleware/slugify/uniqueSlug.spec.js
> +    const umlaut = 'ä'
May be one test:
```
'ÄÖÜäöüß'  -> 'aeoeueaeouuess'
```

2021-01-20 23:22 UTC, Mogge commented on backend/src/middleware/slugify/uniqueSlug.spec.js
> +    const enya = 'ñ'
```
'áàéèíìóòúùñçÁÀÉÈÍÌÓÒÚÙÑÇ' -> 'aaeeiioouuncaaeeiioouunc'
```

2021-01-21 20:51 UTC, Mogge approved these changes
Great! Everything works as expected. Feel free to merge if you think you are done with this PR.

2021-01-21 22:39 UTC, merged