feat [WIP]: Switch User Role As Admin
Ocelot-Social-Community/Ocelot-Social pull request #4136
Opened 2021-01-15 14:44 UTC by Mogge

## 🍰 Pullrequest
An admin can change the role a user has

### Issues
- fixes #4124

### Todo

- [ ] Do we have to ensure that there is at least one admin remaining? What happens if the only admin changes her role to user?

2021-01-15 14:53 UTC, Mogge commented
Can an admin change her own role? This way we could avoid easily that at least one admin is remaining.

2021-01-29 13:24 UTC, Mogge commented
@tippanamadhusudan I added the tests to the backend. I also made sure, that the current user cannot change the own role to make sure that there is always at least one admin left. May be you can catch this in the frontend as well. The backend throws an error when current user tries to change the own role.

2021-02-08 09:45 UTC, Tirokk requested changes
Hey @tippanamadhusudan ,
your first PR is close to get merged into the master !!! 😍

And it’s a really important one, because we need it urgent for the first network `wir.social` going online at the beginning of next week! 🚀🚀💫

If you could follow @Mogge suggestions 👇🏼 you have it quickly ready. 🙏🏼💪🏼

Thank you very much for helping !!! 🍀

2021-02-08 09:45 UTC, Tirokk commented on webapp/graphql/admin/Roles.js
> +        mutation {
If you could solve this by following @Mogge suggestion … @tippanamadhusudan

2021-02-08 09:45 UTC, Tirokk commented on webapp/pages/admin/users.vue
> +                <select
… and try this as well @tippanamadhusudan

2021-02-08 09:45 UTC, Tirokk commented on webapp/pages/admin/users.vue
> +        .mutate({
… and this. @tippanamadhusudan

2021-02-08 09:45 UTC, Tirokk commented on webapp/pages/admin/users.vue
> +        })
I removed the `console.log` already. Hope this is okay … !?
Was a linting error …

2021-02-08 14:14 UTC, tippanamadhusudan commented
Ok, I will make changes according to @mogge.

2021-02-09 15:49 UTC, Tirokk approved these changes
You both got it together !!!

A big thank to @tippanamadhusudan !!! This will go into our first live version of ocelot.social: `wir.social` next week.
Congratulations !!! 🚀🚀💫💫
… and to @Mogge as well for sure! 😘

Just a little hint … 👇🏼

![Gorzilla](https://user-images.githubusercontent.com/25344101/107388913-9b9a1e80-6af6-11eb-9a94-424548dcd7a5.gif)

2021-02-10 12:27 UTC, merged