feat: [WIP] Count Post Views
Ocelot-Social-Community/Ocelot-Social pull request #4248
Opened 2021-02-22 19:51 UTC by Mogge

## 🍰 Pullrequest
Count the number of clicks for posts.

2021-02-25 18:47 UTC, ulfgebhardt requested changes
- One thing I do not understand (see specific review)
- No tests on the frontend (?)

2021-02-25 18:47 UTC, ulfgebhardt commented on backend/src/middleware/userInteractions.js
> +SET relation.count = 1,
I do not get why you would set a count on the relation?! Isn't the relation between a specific user & a specific post, is it?

2021-03-01 11:40 UTC, ulfgebhardt approved these changes

2021-03-01 11:40 UTC, ulfgebhardt approved these changes

2021-03-01 13:54 UTC, Tirokk approved these changes
Hey @Mogge !
We are heading into the future. 🚀🚀🚀

2021-03-01 13:55 UTC, merged