Cypress
Ocelot-Social-Community/Ocelot-Social pull request #4338
Opened 2021-04-03 03:55 UTC by ulfgebhardt

## 🍰 Pullrequest

### Issues

- None

### Todo

- [X] None

2021-04-12 07:57 UTC, Tirokk commented
Hey @ulfgebhardt 
that’s really great that your cared and got it a least partly running. ❤️🍀

2021-04-13 15:06 UTC, Tirokk commented
A reminder for me to test the search feature … @Tirokk

2021-04-14 12:00 UTC, Tirokk requested changes
Hey that’s really supercool @ulfgebhardt  !!!!
Great that we have the Cypress tests back. 🚀🚀🚀💫💫💫

I found problems:

- If I run `yarn cypress:open` and run all the tests of the list I get the error:

<img width="1193" alt="Bildschirmfoto 2021-04-14 um 13 49 26" src="https://user-images.githubusercontent.com/25344101/114706623-7a89c000-9d29-11eb-9ab9-8b63f81ea5bf.png">

- If I run `yarn cypress:run` I get timeout errors like:

<img width="1834" alt="Bildschirmfoto 2021-04-14 um 14 03 02" src="https://user-images.githubusercontent.com/25344101/114707524-9cd00d80-9d2a-11eb-97ae-88e7ce86ac80.png">

2021-04-14 18:42 UTC, ulfgebhardt commented
@Tirokk I fixed the documentation & removed the used commands, but the error you post is a thing of your machine I believe. As I understand it it is only happening if you run all tests together, which is quite memory intensive. If running the tests single works it should be fine.

2021-04-15 06:49 UTC, Tirokk reviewed
Nice that you changed the docs as well @ulfgebhardt ❤️

I understand that you liked to add the line I need for running the tests in Chromium as well.
See below …

2021-04-15 06:49 UTC, Tirokk commented on cypress/cypress.json
>    "baseUrl": "http://localhost:3000",
Add the line

```json
  "chromeWebSecurity": false,
```

here?

2021-04-15 06:52 UTC, Tirokk approved these changes

2021-04-15 10:31 UTC, ulfgebhardt commented on cypress/cypress.json
>    "baseUrl": "http://localhost:3000",
Please commit it @Tirokk <3

2021-04-15 12:31 UTC, Tirokk commented
I pushed the Chromium security fix @ulfgebhardt 
You can merge. ;-)

2021-04-15 13:26 UTC, merged