4548 implement org creation
Ocelot-Social-Community/Ocelot-Social pull request #4803
Opened 2021-11-23 10:50 UTC by Tirokk

## 🍰 Pullrequest

Implement creation of orgs.

### Issues

- fixes #4802

### Todo

- [ ] use the list of social media as template
  - [x] refactor social media list #4771
- [ ] use user settings for creation and listing of the users orgs
  - [ ] put the setting of an org there underneath if you edit it

2022-07-25 13:58 UTC, Mogge requested changes
I am not sure about this. I suggest the following
 * Avoid the complex mixed classes of `profile -> org` and `profile -> user`. Let us keep this as simple as possible. We never worked with this and we cannot know the problems we will face.
 * Let us use a new `Group` model for the groups
 * Let us avoid refactoring in other components, Go straight forward. Later, when we have more time, we can refactor for efficiency and synergies
 * Route `/group/id/slug` for the profile of a group
 * Route `/groups` for the list of groups
 * Copy the user profile to group, to have a base to work on
 * Use the Post template to create/edit Group as blueprint
 * KISS

2022-07-25 13:58 UTC, Mogge commented on backend/src/schema/types/type/Org.gql
> +type Org implements Profile {
Did we agree in not using subcalsses for groups?

2022-07-25 13:58 UTC, Mogge commented on backend/src/schema/types/type/Org.gql
> +  actorId: String
What is this?

2022-07-25 13:58 UTC, Mogge commented on webapp/components/_new/features/MySomethingList/MySomethingList.spec.js
> +          const expectedModalData = expect.objectContaining({
I would prefer this in the expect statement

2022-07-25 13:58 UTC, Mogge commented on webapp/components/_new/features/MySomethingList/MySomethingList.spec.js
> +            expectedModalData,
Place the whole object here. If the test fails, you have to look up for the variable

2022-11-15 10:17 UTC, Tirokk commented
This is now realized by groups

2022-11-15 10:17 UTC, closed without merging