feat: [WIP] 🍰 Implement Group GQL Model And CRUD Resolvers
Ocelot-Social-Community/Ocelot-Social pull request #5139
Opened 2022-08-02 07:08 UTC by Tirokk

## 🍰 Pullrequest

### Issues

- fixes #5131
- relates #5059

### Todo

- [ ] GraphQL
  - [ ] add group settings ( details see https://github.com/Ocelot-Social-Community/Ocelot-Social/issues/5059#user-content-group-settings )
    - [ ] owner/admin
    - [ ] name (title)
    - [ ] slug-name
    - [ ] about (goal)
    - [ ] description
    - [ ] group type
    - [ ] action radius
    - [ ] location
    - [ ] categories: 1-3
    - [ ] members list
  - [ ] `backend/src/models/Groups.js`:
    - [ ] go through and check which properties are needed
    - [ ] test like `backend/src/models/Users.js` are tested with `backend/src/models/User.spec.js`
  - [ ] `backend/src/schema/types/type/Group.gql`:
    - [ ] go through and check what is needed
  - [ ] rename `UserGroup` to `UserRole`?
  - [ ] `Deletable`:
    - [ ] What happens with their groups if users deletes their user profile?
- [ ] cleanup: search for `Wolle`

2022-08-09 09:29 UTC, Elweyn reviewed
Read it and the road seems good!

2022-08-09 14:59 UTC, Tirokk commented
After @Mogge suggestion I do the remainders in the next PR 🍀🙏🏼

2022-08-10 10:38 UTC, Mogge requested changes

2022-08-10 10:38 UTC, Mogge commented on backend/src/schema/resolvers/groups.js
> +        return group
```suggestion
        return result.records.map((record) => record.get('group'))
```

2022-08-10 10:38 UTC, Mogge commented on backend/src/schema/resolvers/groups.js
> +        return group
```suggestion
        return await readTxResultPromise
```

2022-08-10 10:38 UTC, Mogge commented on backend/src/schema/resolvers/groups.spec.js
> +    describe('can find', () => {
```suggestion
    describe('query groups', () => {
```

2022-08-10 10:38 UTC, Mogge commented on backend/src/schema/resolvers/groups.spec.js
> +      it('all', async () => {
```suggestion
      describe('without any filters', () => {
        it('finds all groups', async () => {
```

2022-08-10 10:38 UTC, Mogge commented on backend/src/schema/resolvers/groups.spec.js
> +      it('where user is member (or owner in this case)', async () => {
```suggestion
      decribe(isMember = true', () => {
        it('finds only groups where user is member', async () => {
```

2022-08-10 10:38 UTC, Mogge commented on backend/src/schema/resolvers/groups.spec.js
> +      it('where user is not(!) member', async () => {
```suggestion
      decribe(isMember = false', () => {
        it('finds only groups where user is not(!) member', async () => {
```

2022-08-10 10:38 UTC, Mogge commented on backend/src/schema/resolvers/groups.spec.js
> +    it('"disabled" and "deleted" default to "false"', async () => {
```suggestion
    it('has "disabled" and "deleted" default to "false"', async () => {
```

2022-08-10 10:38 UTC, Mogge commented on backend/src/schema/resolvers/groups.js
> +        throw new UserInputError('To Less Categories!')
```suggestion
        throw new UserInputError('Too view categories!')
```

2022-08-10 10:38 UTC, Mogge commented on backend/src/schema/resolvers/groups.js
> +        throw new UserInputError('To Short Description!')
```suggestion
        throw new UserInputError('Description too short!')
```

2022-08-10 10:38 UTC, Mogge commented on backend/src/schema/resolvers/groups.js
> +        throw new UserInputError('To Many Categories!')
```suggestion
        throw new UserInputError('Too many categories!')
```

2022-08-10 10:38 UTC, Mogge commented on backend/src/schema/types/enum/GroupActionRadius.gql
> +  international
```suggestion
  global
  interplanetary
```

2022-08-10 10:59 UTC, Tirokk commented on backend/src/schema/types/enum/GroupActionRadius.gql
> +  international
Done

2022-08-10 11:00 UTC, Tirokk commented on backend/src/schema/resolvers/groups.js
> +        throw new UserInputError('To Many Categories!')
Done

2022-08-10 11:01 UTC, Tirokk commented on backend/src/schema/resolvers/groups.js
> +        throw new UserInputError('To Short Description!')
Done

2022-08-10 11:02 UTC, Tirokk commented on backend/src/schema/resolvers/groups.js
> +        throw new UserInputError('To Less Categories!')
Done

2022-08-10 11:03 UTC, Tirokk commented on backend/src/schema/resolvers/groups.spec.js
> +    it('"disabled" and "deleted" default to "false"', async () => {
Done

2022-08-10 11:09 UTC, Tirokk commented on backend/src/schema/resolvers/groups.spec.js
> +      it('where user is not(!) member', async () => {
Done

2022-08-10 11:09 UTC, Tirokk commented on backend/src/schema/resolvers/groups.spec.js
> +      it('where user is member (or owner in this case)', async () => {
Done

2022-08-10 11:10 UTC, Tirokk commented on backend/src/schema/resolvers/groups.spec.js
> +      it('all', async () => {
Done

2022-08-10 11:11 UTC, Tirokk commented on backend/src/schema/resolvers/groups.spec.js
> +    describe('can find', () => {
Done

2022-08-10 17:36 UTC, Mogge approved these changes

2022-08-15 09:22 UTC, Mogge approved these changes

2022-08-15 11:35 UTC, merged