fist step mobile footer menu to heder menu
Ocelot-Social-Community/Ocelot-Social pull request #5524
Opened 2022-10-19 10:23 UTC by ogerly

## 🍰 Pull Request

fist step,  if mobile,  footer menu to heder menu

### Issues
 
- fixes #4732

2022-10-19 10:23 UTC, ogerly commented
https://user-images.githubusercontent.com/1324583/196665334-33fff2fd-2c05-41f9-b216-ab84b223fa71.mp4

2022-10-19 19:29 UTC, ogerly commented
ok ... i solved it. next to the search input in the header the filter button is only visible on the index. if you move in the network then the filter button disappears ... that's why i didn't see it ...

2022-10-20 12:27 UTC, ogerly commented
![Bildschirmfoto vom 2022-10-20 09-38-02](https://user-images.githubusercontent.com/1324583/196948355-f9a9a45d-ac71-465a-8a38-913e4c16bae3.png)

2022-10-21 05:31 UTC, Tirokk requested changes
This looks very nice 😍

- There is a width where the footer is still there and the hamurger-menu appears already. I made a suggestion in the code how to avoid this.
- The space between the items of the header menu should be the same as in the very good looking footer menu, see screenshot.
- Can we get the search field etc. already in the second row if the hamburger-menu appears, see screen shot. If possible, that would be perfect. If not we can life with it for now.

<img width="640" alt="Bildschirmfoto 2022-10-21 um 07 18 32" src="https://user-images.githubusercontent.com/25344101/197119035-9fb52907-a8ac-4375-8886-bb434ac16199.png">

2022-10-21 05:31 UTC, Tirokk commented on webapp/components/PageFooter/PageFooter.vue
> +}
```suggestion
@media only screen and (max-width: 810px) {
  .ds-footer {
    display: none;
  }
}
```

Then the footer menu doeas not appear at the same time as the footer.

2022-10-22 06:12 UTC, Tirokk approved these changes
Hey @ogerly wonderful !!!

Nice how you refactoed and restructured the menu code 😍

I approve 🚀🚀💫💫

2022-10-22 06:14 UTC, Tirokk commented
And allow myself to merge, because then I can go more qucikly ahead …
Hope that's okay.

2022-10-22 06:15 UTC, merged