header menu to component
Ocelot-Social-Community/Ocelot-Social pull request #5546
Opened 2022-10-22 07:46 UTC by ogerly

## 🍰 Pullrequest

I have packed the header menu from the layout /default into a componente. 
on the layout/default maxMobileWidth: 811 is determined in a central position and showMobileMenu is passed through to the menu. 
the switching on and off of header mobil menu and footer is only controlled on the layout default. i deleted all css that did that. so the default/layout is now very clear and we only have to change the value in one place if necessary.

2022-10-22 10:04 UTC, Tirokk requested changes
An upfront review only because I've accidently have seen it.

Just let us change it next week with the other things which may appear …

2022-10-22 10:04 UTC, Tirokk commented on webapp/layouts/default.vue
> +      return this.windowWidth < this.maxMobileWidth
```suggestion
      return this.windowWidth <= this.maxMobileWidth
```

That fits better to the name `maxMobileWidth` and the logic is more consitent if we use `810px` all over the place and not `811px`.

2022-10-22 10:04 UTC, Tirokk commented on webapp/layouts/default.vue
> +      maxMobileWidth: 811,
```suggestion
      maxMobileWidth: 810,
```

See comment below.

2022-10-28 11:33 UTC, Mogge approved these changes

2022-10-28 11:45 UTC, merged