feat(webapp): 🍰 Search Users To Add To Group
Ocelot-Social-Community/Ocelot-Social pull request #5652
Opened 2022-11-08 08:05 UTC by Mogge

## 🍰 Pullrequest

### Issues
- fixes #5629 

### Todo

- [X] None

2022-11-10 09:30 UTC, ogerly commented
TODO: 

- the id of the selected user is written into the input field after clicking. 
- when searching again, the user is still in the selection. 

https://user-images.githubusercontent.com/1324583/201053039-a30b15c3-35c5-4555-a9bd-508cc7189267.mp4

2022-11-23 15:01 UTC, Tirokk requested changes
Hey, cool !!! @Mogge @ogerly 

I have some questions and some suggestions …

If I add a user who is already a group member their ID appears in the search field:

<img width="1646" alt="Bildschirmfoto 2022-11-23 um 14 50 27" src="https://user-images.githubusercontent.com/25344101/203563973-a2449bf2-76cb-40e0-afd3-d4290dcb40b9.png">

2022-11-23 15:25 UTC, Mogge commented on webapp/locales/de.json
> +      "confirm": "Bestätigen",
No. May be we want to change the title of the modal. I am not happy with the title but had no better idea so far.

2022-11-24 07:46 UTC, Tirokk requested changes
In general it looks really good! @Mogge 

The user ID still appears if you add a user who is already member.
Did you mean you have healed this or must it be that way?

<img width="1646" alt="Bildschirmfoto 2022-11-24 um 08 34 51" src="https://user-images.githubusercontent.com/25344101/203723245-27604ef9-aec9-459e-a4c7-a051d92567c1.png">

2022-11-24 07:46 UTC, Tirokk commented on webapp/locales/en.json
> +      "userAlreadyMember": "User “{name}” is already a member"
```suggestion
      "userAlreadyMember": "User “{name}” is already a member!"
```

2022-11-24 07:46 UTC, Tirokk commented on webapp/locales/de.json
> +      "userAlreadyMember": "Nutzer „{name}“ ist bereits Mitglied"
```suggestion
      "userAlreadyMember": "Benutzer „{name}“ ist bereits Mitglied!"
```

2022-11-24 16:28 UTC, Tirokk approved these changes
Than I approve dear and we have to fix the ID in the search field later.
Please make an issue for it.

🚀🚀🌟🌟

2022-11-24 17:05 UTC, merged