feat(webapp): map
Ocelot-Social-Community/Ocelot-Social pull request #5843
Opened 2023-01-04 12:35 UTC by ulfgebhardt

## 🍰 Pullrequest

Basic implementation of `v-mapbox`- got thinks working

### Issues

- fixes #5807
- relates #4546

### Todo

- [x] have map icon on header
  - [x] map shall be reached by globus in header menu
    - [x] the one of the language menu
      - [ ] in the size of the avatar image
      - [x] tooltip:
        - de: `Landkarte anzeigen`
        - en: `Show map`
    - [x] (no) do we use a different icon in the language menu then?
- [x] may have a hint in the settings that by entering my location I a gree to show my location on the map
  - [x] and maybe hint that the position is not very specific
- [x] do we need the package `@mapbox/mapbox-gl-language`?
  - [x] tried, but does not work yet
- [x] implement `MAPBOX_TOKEN` in webapp config
  - [x] switch map off if there is no `MAPBOX_TOKEN`?
    - [x] header icon
    - [x] page
  - [x] implement it in docker compose and deployment all over the place
- [x] translate several texts
- [x] map optimization: see #5901
  - [ ] have a legend?
- [x] we need Node v16.5.0 or higher in webapp for the package `v-mapbox@legacy`
  - [x] we use Node v16.19.0, see #5842 
    - Node v19.3.0 was not working
- [x] mention the Node version in webapp README?
  - [x] have the latest version? See issue #5902
- [x] rebranding
  - changed map style buttons from `<ds-button>` to `<base-button>`
    - [x] adjust look of `inactive` button
    - [ ] try to implement `inactive` state into `BaseButton.vue`
      - !!! the map style inactive buttons don't have the right color
- [x] tests, see followup issue #5927
  - [x] decrease coverage to `61%` in webapp for now
- [x] cleanup: search for `Wolle`

2023-01-05 09:03 UTC, Tirokk commented on webapp/package.json
> +    "@nuxtjs/composition-api": "0.32.0",
Thanks for your work @ulfgebhardt
I have tried that as well and got a different error messages.

I try again.

2023-01-25 16:32 UTC, Tirokk commented on webapp/graphql/groups.js
>          location {
Fragment `location` should not have the same name as propety `location` I guess.
Sometime we have a GQL error seems related to this, see issue.

2023-02-03 17:10 UTC, Mogge requested changes
Some smaller things to start with

2023-02-03 17:10 UTC, Mogge commented on webapp/utils/utils.js
> +export const objectValuesToArray = (obj) => {
This is https://docs-lodash.com/v4/to-array/
Please import it from there

2023-02-03 19:46 UTC, Mogge approved these changes

2023-02-03 19:49 UTC, Mogge approved these changes

2023-02-03 21:05 UTC, merged