[WIP] feature(webapp): filter menu in content page
Ocelot-Social-Community/Ocelot-Social pull request #5886
Opened 2023-01-23 19:56 UTC by ogerly

## 🍰 Pullrequest
Es gibt jetzt im Content Page bereich einen Button zum filtern von Beiträgen. 

Ich habe folgenden Vorschlag. Da wir in der mobilen variante wenig platz haben. habe ich folgende drei zustände. 

- Alles ist ausgewählt (Kein filter gesetzt)
- ![Bildschirmfoto vom 2023-01-23 20-32-20](https://user-images.githubusercontent.com/1324583/214132547-57be250e-6687-4e9b-b553-0e6096181be4.png)

- ein Filter ist gesetzt 
![Bildschirmfoto vom 2023-01-23 20-32-43](https://user-images.githubusercontent.com/1324583/214132545-f2dd8a70-7f18-412c-9752-252d6097bd1a.png)
- ein Filter ist gesetzt (suche von Accounts denen ich folge)
![Bildschirmfoto vom 2023-01-23 20-32-54](https://user-images.githubusercontent.com/1324583/214132541-6d33569a-9cee-4069-9e70-31d525edaad9.png)

- mehrere Filter sind gesetzt (suche von Accounts denen ich folge)
![Bildschirmfoto vom 2023-01-23 20-35-52](https://user-images.githubusercontent.com/1324583/214133036-8ea25295-317c-4e04-a9dd-ee2cf461ad48.png)

![Bildschirmfoto vom 2023-01-23 20-35-36](https://user-images.githubusercontent.com/1324583/214133042-c098f3a3-8ff3-4c3e-be3c-66b5815c2707.png)

### Issues
<!-- Which Issues does this fix, which are related?
- fixes #5818

2023-01-25 10:31 UTC, ogerly commented
https://user-images.githubusercontent.com/1324583/214540671-d471b30c-9b30-43ba-9131-07f336240b5d.mp4

2023-01-30 11:49 UTC, Mogge requested changes
Think about slots for the buttons instead of the ifs

2023-01-30 11:49 UTC, Mogge commented on webapp/locales/en.json
> +      "myTheme": "My Themes",
```suggestion
      "myTopics": "My topics",
```

2023-01-30 11:49 UTC, Mogge commented on webapp/locales/de.json
> +      "myTheme": "Meine Themen",
```suggestion
      "myTopics": "Meine Themen",
```

2023-01-30 11:49 UTC, Mogge commented on webapp/pages/index.vue
> +            title="Filter löschen"
locale?

2023-01-30 11:49 UTC, Mogge commented on webapp/pages/index.vue
> +            {{ $t('contribution.filterMasonryGrid.myTheme') }}
```suggestion
            {{ $t('contribution.filterMasonryGrid.myTopics') }}
```

2023-01-31 09:17 UTC, ogerly commented on webapp/locales/en.json
> +      "myTheme": "My Themes",
done

2023-01-31 09:18 UTC, ogerly commented on webapp/locales/de.json
> +      "myTheme": "Meine Themen",
done

2023-01-31 09:18 UTC, ogerly commented on webapp/pages/index.vue
> +            {{ $t('contribution.filterMasonryGrid.myTheme') }}
done

2023-01-31 09:27 UTC, ogerly commented on webapp/pages/index.vue
> +            title="Filter löschen"
done

2023-02-06 11:41 UTC, merged