[WIP] test(other): ugragde cypress to v10
Ocelot-Social-Community/Ocelot-Social pull request #6008
Opened 2023-02-21 17:51 UTC by mahula

## 🍰 Pullrequest
Upgrade the Cypress framework to v10

### Issues

- None

### Todo

- [X] None

2023-06-03 08:25 UTC, mahula commented on cypress/cypress.config.js
> +const { parsed } = dotenv.config({ path: '../backend/.env' })
Research, if there is a better practice for Cypress wil be covered in issue  #6374.

2023-06-05 18:20 UTC, Elweyn requested changes
Works for me!
Just the import of gql can be removed!

2023-06-05 18:20 UTC, Elweyn commented on cypress/support/step_definitions/Moderation.ReportContent/somebody_reported_the_following_posts.js
> +import { gql } from '../../../../backend/src/helpers/jest'
```suggestion
```

2023-06-05 18:58 UTC, ulfgebhardt commented
Try updating `neode` in `root/package.json ` -> to avoid: 
```
Image: typeof Cypress !== 'undefined' ? require('./Image.js') : require('./Image.js').default,
```

2023-06-05 20:39 UTC, mahula commented
> Try updating `neode` in `root/package.json ` -> to avoid:
> 
> ```
> Image: typeof Cypress !== 'undefined' ? require('./Image.js') : require('./Image.js').default,
> ```

Does neode v0.4.9 really solve this?

2023-06-06 11:45 UTC, Tirokk commented
I just tried it out to see if it runs on my machine and get this error:

<img width="1728" alt="Bildschirmfoto 2023-06-06 um 13 39 20" src="https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/25344101/3fbcece4-1f59-4d86-b15a-e16a1a2adb99">

2023-06-06 14:03 UTC, Elweyn approved these changes

2023-06-06 14:05 UTC, merged