docs(other): correct **/README.md
Ocelot-Social-Community/Ocelot-Social pull request #6059
Opened 2023-02-28 12:04 UTC by Elweyn

## 🍰 Pullrequest

### Issues

- None

### Todo

- [X] Contraint to Constraint
- [X] Indexes to Indices
- [X] Add migrations up to docus

2023-03-06 08:58 UTC, mahula approved these changes

2023-03-06 10:43 UTC, Mogge approved these changes

2023-03-06 17:15 UTC, Tirokk requested changes
I have some suggestions.

PS: An indice is the small number behind a mathematical variable or coeffecent. An index is a kind of a register.

2023-03-06 17:15 UTC, Tirokk commented on CONTRIBUTING.md
> +# only once: init admin user and create indices and constraints in Neo4j database
Indexes is the correct namimg, see headline of:
https://neo4j.com/docs/cypher-manual/current/indexes-for-search-performance/

```suggestion
# only once: init admin user and create indexes and constraints in Neo4j database
```

2023-03-06 17:15 UTC, Tirokk commented on CONTRIBUTING.md
> +# only once: init admin user and create indices and constraints in Neo4j database
same same

```suggestion
# only once: init admin user and create indexes and constraints in Neo4j database
```

2023-03-06 17:15 UTC, Tirokk commented on README.md
> +$ docker-compose exec backend yarn run db:migrate up
Without dash is the modern command, see:
https://docs.docker.com/compose/reference/

```suggestion
$ docker compose exec backend yarn run db:migrate init
$ docker compose exec backend yarn run db:migrate up
```

2023-03-06 17:15 UTC, Tirokk commented on backend/README.md
> +# if container is not running, run this command to set up your database indices and constraints
same same

```suggestion
# if container is not running, run this command to set up your database indexes and constraints
```

2023-03-06 17:15 UTC, Tirokk commented on backend/README.md
> +# And then upgrade the indices and const
```suggestion
# And then upgrade the indexes and const
```

2023-03-06 17:15 UTC, Tirokk commented on deployment/DOCKER_MORE_CLOSELY.md
> +# only once: init admin user and create indices and constraints in Neo4j database
```suggestion
# only once: init admin user and create indexes and constraints in Neo4j database
```

2023-03-06 17:15 UTC, Tirokk commented on neo4j/README.md
> +If indices or constraints are missing or not set correctly, the browser search will not work or the database seed for development will not work.
```suggestion
If indexes or constraints are missing or not set correctly, the browser search will not work or the database seed for development will not work.
```

2023-03-06 17:15 UTC, Tirokk commented on neo4j/README.md
> +The indices and constraints of our database are set in `backend/src/db/migrate/store.js`.
```suggestion
The indexes and constraints of our database are set in `backend/src/db/migrate/store.js`.
```

2023-03-06 17:15 UTC, Tirokk commented on neo4j/README.md
> +This command initializes the Admin user and creates all necessary indices and constraints in the Neo4j database.
```suggestion
This command initializes the Admin user and creates all necessary indexes and constraints in the Neo4j database.
```

2023-03-06 17:15 UTC, Tirokk commented on neo4j/README.md
> +***Cypher commands to show indices and constraints***
```suggestion
***Cypher commands to show indexes and constraints***
```

2023-03-06 17:15 UTC, Tirokk commented on neo4j/README.md
> +# show all indices and constraints
```suggestion
# show all indexes and constraints
```

2023-03-06 17:15 UTC, Tirokk commented on neo4j/README.md
> +# show all indices
```suggestion
# show all indexes
```

2023-03-06 17:15 UTC, Tirokk commented on neo4j/README.md
> +***Cypher commands to create and drop indices and constraints***
```suggestion
***Cypher commands to create and drop indexes and constraints***
```

2023-03-06 17:15 UTC, Tirokk commented on neo4j/README.md
> +# create indices
```suggestion
# create indexes
```

2023-03-06 17:15 UTC, Tirokk commented on neo4j/README.md
> +# drop all indices and constraints
```suggestion
# drop all indexes and constraints
```

2023-03-08 15:40 UTC, Tirokk requested changes
Sorry, I found one additional.
Then it's okay.

2023-03-08 15:40 UTC, Tirokk commented on backend/README.md
> +Database indices and constraints need to be created and upgraded when the database and the backend are running:
```suggestion
Database indexes and constraints need to be created and upgraded when the database and the backend are running:
```

2023-03-13 06:06 UTC, Elweyn commented on backend/README.md
>  ### Database Indices and Constraints
```suggestion
### Database Indexes and Constraints
```

2023-03-14 09:04 UTC, merged