fix(webapp): change icon color of active topics (categories) of post teaser
Ocelot-Social-Community/Ocelot-Social pull request #6112
Opened 2023-03-09 14:27 UTC by Tirokk

## 🍰 Pullrequest

Change icon color of active topics (categories) of post teaser.

### Issues

- fixes #5983

### Todo

- [x] none

2023-03-13 13:24 UTC, Elweyn approved these changes

2023-03-13 14:48 UTC, Elweyn requested changes

2023-03-14 06:46 UTC, Tirokk commented on webapp/components/Category/index.vue
> +  background-color: $color-primary-active;
`$color-primary-inverse` is the color we should use in situations like this to have not an absolut hart white contrast, but a little softer contrast instead.

2023-03-14 09:06 UTC, Elweyn approved these changes

2023-03-14 09:51 UTC, merged