feature(webapp);[WIP] feature refactor notification page
Ocelot-Social-Community/Ocelot-Social pull request #6116
Opened 2023-03-10 20:23 UTC by maeckes-infinitylabs

## 🍰 Pullrequest
Refactors the notification page to add better visibility for mobile devices. 
It now uses a mixture of CSS Grid and Flex to have a responsive table for desktop views.
For mobile devices it breaks the table down in notification-row items for a better overview.

### Issues

- None

### Todo

- [X] None

2023-03-13 15:03 UTC, Elweyn requested changes
It is more a question to everyone do we use ``f`` or ``n`` in a loop or do we use the full descriptiv name, I prefer the second.

2023-03-13 15:03 UTC, Elweyn commented on webapp/components/NotificationsTable/NotificationsTable.vue
> +                          :class="{ 'notification-status': n.read }"
```suggestion
                          :user="notification.from.author"
                          :date-time="notification.from.createdAt"
                          :class="{ 'notification-status': notification.read }"
```

2023-03-13 15:03 UTC, Elweyn commented on webapp/components/NotificationsTable/NotificationsTable.vue
> +                      {{ $t(`notifications.reason.${n.reason}`) }}
```suggestion
                    <ds-text :class="{ 'notification-status': notification.read, reason: true }">
                      {{ $t(`notifications.reason.${notification.reason}`) }}
```

2023-03-13 15:55 UTC, maeckes-infinitylabs commented
@Elweyn I fully agree with you to use full descriptive names for variables and added your suggestions

2023-03-13 16:21 UTC, Elweyn approved these changes
Great, I have no more objections.

2023-03-14 07:24 UTC, Tirokk approved these changes
Hey @maeckes-infinitylabs 

that looks really cool and breaks nicely into the mobile style.
Great 😍

I approve 🚀🚀💫💫

2023-03-14 19:21 UTC, merged