6266 event create design optimization
Ocelot-Social-Community/Ocelot-Social pull request #6270
Opened 2023-04-26 11:48 UTC by ogerly

## 🍰 Pullrequest
- tab post
- datepicker, hide before today, hide seconds, minute steps 15 min
 

### Issues
- fixes #6266 

![Bildschirmfoto vom 2023-04-26 13-45-28](https://user-images.githubusercontent.com/1324583/234565792-0a36ec7e-1c9f-4a12-b131-23a1dc64a47e.png)

![Bildschirmfoto vom 2023-04-26 13-45-45](https://user-images.githubusercontent.com/1324583/234565786-6900b07b-fb7e-4558-aec6-3b646db5fc1a.png)

2023-04-26 12:56 UTC, ogerly commented
![Bildschirmfoto vom 2023-04-26 14-55-52](https://user-images.githubusercontent.com/1324583/234581543-3de1a5a2-88af-4c66-89c1-0e01105ea2e6.png)
![Bildschirmfoto vom 2023-04-26 14-55-25](https://user-images.githubusercontent.com/1324583/234581552-75154739-84bf-4d32-956a-6d07ced79794.png)
![Bildschirmfoto vom 2023-04-26 14-55-03](https://user-images.githubusercontent.com/1324583/234581559-5304a4bd-86dc-4e61-9d96-23fc8f3b65e0.png)

2023-05-13 10:10 UTC, Elweyn requested changes

2023-05-13 10:10 UTC, Elweyn commented on webapp/graphql/PostMutations.js
> -        $image: ImageInput
why did this get removed?

2023-05-13 10:10 UTC, Elweyn commented on webapp/graphql/PostMutations.js
> -          image: $image
This also got removed somehow

2023-05-13 10:13 UTC, Elweyn approved these changes
This view of the event location and dates are good, maybe we want it in another place of the teaser but we would make this in a new issue

2023-05-13 10:13 UTC, Elweyn commented on webapp/graphql/PostMutations.js
> -        $image: ImageInput
Got deleted somewhere on the process but think is still needed

2023-05-13 10:13 UTC, Elweyn commented on webapp/graphql/PostMutations.js
> -          image: $image
Got deleted somewhere on the process but think is still needed

2023-05-17 09:03 UTC, merged