Add creatEvent to the update post so the form has event specific fields.
Ocelot-Social-Community/Ocelot-Social pull request #6358
Opened 2023-05-31 09:03 UTC by Elweyn

## 🍰 Pullrequest

Now you can edit the event fields when updating an event.

### Issues

- fixes #6339 

### Todo

- [X] None

2023-06-01 08:51 UTC, ulfgebhardt commented on webapp/pages/post/edit/_id.vue
> +          :creatEvent="contribution && contribution.postType[0] === 'Event'"
```suggestion
          :createEvent="contribution && contribution.postType[0] === 'Event'"
```

2023-06-05 11:25 UTC, mahula submitted a review, later dismissed
Changing/updation an event in the frontend does send all data in the request.
But the venue and location are not updated.
'Please revisit `backend/src/schema/resolvers/posts.js`

2023-06-05 13:07 UTC, Tirokk requested changes
Prereview

<img width="818" alt="Bildschirmfoto 2023-06-05 um 11 46 36" src="https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/25344101/0bacf936-bf47-4808-8fe2-7c6c5a686a25">

<img width="806" alt="Bildschirmfoto 2023-06-05 um 12 12 14" src="https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/25344101/79391735-2165-44e3-bf78-fc5251525eef">

<img width="809" alt="Bildschirmfoto 2023-06-05 um 12 14 26" src="https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/25344101/191c9a07-02f9-43b0-b497-9e7884bef766">

<img width="806" alt="Bildschirmfoto 2023-06-05 um 15 02 14" src="https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/25344101/810ce95e-162a-4e92-bc07-e5513d54c77a">

2023-06-05 18:28 UTC, ulfgebhardt approved these changes

2023-06-06 07:57 UTC, Tirokk commented on webapp/pages/post/edit/_id.spec.js
> +                ],
Then event is not tested?

2023-06-06 08:44 UTC, Tirokk commented on webapp/locales/de.json
> +      "event": "Bearbeite deine Veranstaltung",
I recompiled and now it's okay 👍🏼

2023-06-06 08:44 UTC, Tirokk commented on webapp/locales/en.json
> +      "event": "Edit Your Event",
I recompiled and now it's okay 👍🏼

2023-06-06 10:26 UTC, Tirokk requested changes
I have still two little suggestions

2023-06-06 10:26 UTC, Tirokk commented on webapp/pages/post/_id/_slug/index.vue
>                  </span>
Hint: Because row 67 and 71 are the same we could move it as one line before the first `span`.

2023-06-06 10:26 UTC, Tirokk commented on webapp/pages/post/_id/_slug/index.vue
> +              </ds-text-->
delete the comment?

2023-06-07 15:04 UTC, Tirokk commented on webapp/pages/post/_id/_slug/index.vue
>                  </span>
I solved this in my other PR

2023-06-07 15:04 UTC, Tirokk commented on webapp/pages/post/_id/_slug/index.vue
> +              </ds-text-->
I solved this in my other PR

2023-06-08 07:04 UTC, Elweyn commented
Has been taken over in new PR #6381

2023-06-08 07:04 UTC, closed without merging