fix(webapp): fix event teaser date from start to end by new components
Ocelot-Social-Community/Ocelot-Social pull request #6385
Opened 2023-06-07 12:19 UTC by Tirokk

## 🍰 Pullrequest

Fix event teaser date from start to end by new components.

### Issues

- fixes #6379 

### Todo

- [ ] create component for date range
- [ ] create component for location

2023-06-07 15:59 UTC, Mogge requested changes

2023-06-07 15:59 UTC, Mogge commented on webapp/components/DateTimeRange/DateTimeRange.vue
> +    isSameDay() {
Do you use the same name as the imported  `isSameDate` method on purpose? This might be confusing. Sure that there are no problems?

2023-06-07 15:59 UTC, Mogge commented on webapp/components/DateTimeRange/DateTimeRange.vue
> +      let startDateFormat = 'dd.MM.yyyy'
This is German. This must be localized.

2023-06-07 18:06 UTC, Tirokk commented
I find this ugly and have to talk about. @Elweyn @maeckes-infinitylabs @ogerly 

<img width="375" alt="Bildschirmfoto 2023-06-07 um 20 04 44" src="https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/25344101/0273ed22-d414-4a06-88d5-651a698491ba">

2023-06-08 14:12 UTC, Elweyn commented
![image](https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/33051975/4ef342a6-b10f-4863-a4f8-cafccdcdd2ca)

2023-06-08 17:03 UTC, Elweyn approved these changes
Please make follow issue for Unit Test of the components

2023-06-08 17:47 UTC, Tirokk commented
> Please make follow issue for Unit Test of the components

Done here #6407

2023-06-08 18:53 UTC, Mogge approved these changes

2023-06-08 19:04 UTC, merged