refactor(webapp): refactor filter menu
Ocelot-Social-Community/Ocelot-Social pull request #6535
Opened 2023-07-11 12:29 UTC by maeckes-infinitylabs

## 🍰 Pullrequest

Makes some visual adjustments and text updates for filter menu

![image](https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/57147781/bc1e0f1c-1245-4b07-8558-68ef0d769b83)

### Issues

- relates #6500

### Todo

- [X] None

2023-07-12 07:18 UTC, Elweyn requested changes

2023-07-12 07:18 UTC, Elweyn commented on webapp/components/FilterMenu/PostTypeFilter.vue
> +        <base-button
Here eher doch labeled-button. Aber ich frage nochmal Yunite

2023-07-12 09:49 UTC, Elweyn commented
![image](https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/33051975/6ca0b614-d6f4-4ad1-b065-1e9316c11444)

2023-07-19 19:56 UTC, maeckes-infinitylabs commented
I updated the UI:

![image](https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/57147781/0f63131d-9cf5-4083-ae0f-e179ff77d819)

2023-07-19 19:56 UTC, maeckes-infinitylabs commented on webapp/components/FilterMenu/PostTypeFilter.vue
> +        <base-button
see newest commit

2023-07-20 08:06 UTC, maeckes-infinitylabs commented
Next proposal:

![image](https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/57147781/28104db1-b434-4757-b8ff-c168933080ab)

2023-07-26 15:20 UTC, Tirokk requested changes
Looks really cool! @maeckes-infinitylabs 😍

But I have to request changes. A little I made my self.

The following are hints instead of labels and not all of them I made a code suggestion for:

<img width="1053" alt="Bildschirmfoto 2023-07-26 um 17 12 27" src="https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/25344101/116e2e00-3195-400a-8163-4c5e40f5afb2">

<img width="1051" alt="Bildschirmfoto 2023-07-26 um 17 11 06" src="https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/25344101/a2aba27d-bfd5-4e22-b71f-3c8c49e65f99">

Just in case there is time for it. Otherwise we do it in the next release. No problem:
See issue #6644

2023-07-26 15:20 UTC, Tirokk commented on webapp/components/FilterMenu/EventsByFilter.vue
> +          {{ $t('filter-menu.ended.onlyEnded.hint') }}
I think this would be correct.

```suggestion
          {{ $t('filter-menu.ended.onlyEnded.label') }}
```

2023-07-28 11:27 UTC, maeckes-infinitylabs commented on webapp/components/FilterMenu/EventsByFilter.vue
> +          {{ $t('filter-menu.ended.all.hint') }}
done

2023-07-28 11:27 UTC, maeckes-infinitylabs commented on webapp/components/FilterMenu/EventsByFilter.vue
> +          {{ $t('filter-menu.ended.onlyEnded.hint') }}
done

2023-07-28 12:06 UTC, maeckes-infinitylabs commented
> Just in case there is time for it. Otherwise we do it in the next release. No problem: See issue #6644

![image](https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/57147781/1bfa2393-997a-4361-980e-529253931d85)

added #6644 to this PR

2023-07-31 08:43 UTC, Elweyn commented
Somehow it is strange in german cause of "Veranstalltung" is so long:
![image](https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/33051975/fd94f157-e6cf-473e-b7dd-08d495f4540e)

2023-07-31 12:19 UTC, maeckes-infinitylabs commented
![image](https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/57147781/803a5db5-aa72-498f-aa61-3580764f029d)

added feedback and the padding for the filter list

2023-07-31 14:53 UTC, merged