fix(webapp): add jsconfig.json to navigate in webapp.
Ocelot-Social-Community/Ocelot-Social pull request #6645
Opened 2023-07-27 07:55 UTC by Elweyn

## 🍰 Pullrequest

In VsCode the Vue file could not be navigated through, 
with this PR it should be fixed.

### Issues

- None

### Todo

- [X] Development jump to imported vue files

2023-07-31 09:10 UTC, mahula requested changes

2023-07-31 09:10 UTC, mahula commented on webapp/jsconfig.json
> +// tsconfig.json
```suggestion
```

2023-08-04 05:11 UTC, Elweyn commented
@mahula OK let's check which one are working and which one need to be defined!

2023-09-12 06:15 UTC, mahula approved these changes

2023-09-12 06:43 UTC, merged