fix(webapp): try to fix avatars
Ocelot-Social-Community/Ocelot-Social pull request #6660
Opened 2023-08-07 16:18 UTC by Tirokk

## 🍰 Pullrequest

Try to fix avatars.

### Issues

- relates #6659

### Todo

- [X] None

2023-08-08 05:50 UTC, Elweyn requested changes
This fixes the user profil picture in the chat room, but the room doesn't get the image!
![image](https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/33051975/8b364dfd-d659-4ba1-b445-b4c8d68b2245)

2023-08-08 10:24 UTC, Elweyn approved these changes

2023-08-08 13:32 UTC, Tirokk reviewed
Works most of the time.
Only if I scroll up in the messages until relead then the old message avatars do disappear.

<img width="1654" alt="Bildschirmfoto 2023-08-08 um 15 13 20" src="https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/25344101/11567d77-0b7d-4983-bda3-b674229b1641">

<img width="1654" alt="Bildschirmfoto 2023-08-08 um 15 13 35" src="https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/25344101/5620456f-daeb-4d7d-b876-d95844b63198">

2023-08-09 09:24 UTC, Elweyn approved these changes

2023-08-09 09:24 UTC, merged