chore(other): remove obsolete version element from all docker yaml files
Ocelot-Social-Community/Ocelot-Social pull request #7564
Opened 2024-06-22 19:34 UTC by mahula

## 🍰 Pullrequest

### Issues

- None

### Todo

- [X] None

2024-06-22 19:48 UTC, roschaefer requested changes
![typo](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExaTJjdTJ0YnhkODEwN3B6cnAxZ3dlajN2N3V2Y25oOWRlcjI0NWU5dSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/wA6aYAO3jH6RmUIBYs/giphy.gif)

So close, but I have to request changes because of the typo.

2024-06-22 19:48 UTC, roschaefer commented on docker-compose.maintenance.yml
> +ervices:
```suggestion
services:
```

:sob: this will be a "Request changes"

2024-07-06 18:17 UTC, Tirokk submitted a review, later dismissed
Cool @roschaefer !
Looks good.

Therefore I approve 🚀💫

2024-07-06 18:21 UTC, Tirokk commented
Sorry, seems that coordinates of MapBox have changed again a little bit.
Just adjust them in the tests or do a separate PR to fix it. @mahula

2024-07-06 19:19 UTC, mahula commented
> Sorry, seems that coordinates of MapBox have changed again a little bit. Just adjust them in the tests or do a separate PR to fix it. @mahula
> 
> https://github.com/Ocelot-Social-Community/Ocelot-Social/actions/runs/9662278558/job/26651955956?pr=7564

Please open a separate bug issue @Tirokk , since this is not related to this pull request.
And with time at hand someone ofus will take care of it.

2024-08-30 11:43 UTC, Tirokk approved these changes
Sorry, haven't remembered that you have already done @mahula

2024-08-30 12:32 UTC, merged